name: .NET
env:
  PUBLISH_DIR: ./output
  PUBLISH_DIR_WWWROOT: ./output/wwwroot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
      shell: bash
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/BlazorWasmApp/BlazorWasmApp/BlazorWasmApp.csproj
    - name: Build
      run: dotnet publish ./src/BlazorWasmApp/BlazorWasmApp/BlazorWasmApp.csproj --no-restore --configuration Release --output  ${{ env.PUBLISH_DIR }}
    - name: Rewrite base href
      if: success()
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR_WWWROOT }}/index.html
        base_href: ${{ github.event.repository.name }}
    - name: Add .nojekyll file
      run: touch ${{ env.PUBLISH_DIR_WWWROOT }}/.nojekyll
    - name: Commit to GitHub pages Repo
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR_WWWROOT }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
